import type {
  ErrorOptions,
  Exact,
  IsObject,
  Merge,
  RemoveFixed,
  ResolvedErrorOptions,
  Simplify,
  SimplifyDeep,
} from "./types";

import { BaseError, type ErrorContext } from "./base";

type ErrorInstance<
  Name extends string,
  Code extends string,
  Message extends string,
  Context,
> = Context extends ErrorContext
  ? BaseError<Code, Message, Context> & {
      readonly name: Name;
    }
  : never;

/**
 * Represents the options that remain available to the caller after
 * applying the factory's fixed values.
 *
 * Fixed leaf properties are removed completely. Fixed object properties
 * remain available only through their non-fixed descendants.
 */
type RemainingErrorOptions<Fixed extends ErrorOptions> = Simplify<
  Omit<ErrorOptions, keyof Fixed> & {
    [
      Key in keyof Fixed & keyof ErrorOptions as IsObject<Fixed[Key]> extends true ? Key : never
    ]?: RemoveFixed<ErrorOptions[Key], Fixed[Key]>;
  }
>;

/**
 * Resolves the final error code from factory configuration and call options.
 *
 * The precedence is:
 *
 * `fixed.code` → `options.code` → `defaults.code`
 */
type ErrorCode<
  Fixed extends ErrorOptions,
  Defaults extends ErrorOptions,
  Options extends ErrorOptions,
> = Extract<ResolvedErrorOptions<Fixed, Defaults, Options>["code"], string>;

/**
 * Resolves the final error message from factory configuration and call options.
 *
 * The precedence is:
 *
 * `fixed.message` → `options.message` → `defaults.message`
 */
type ErrorMessage<
  Fixed extends ErrorOptions,
  Defaults extends ErrorOptions,
  Options extends ErrorOptions,
> = Extract<ResolvedErrorOptions<Fixed, Defaults, Options>["message"], string>;

type ResolvedContext<
  Defaults extends ErrorOptions,
  Options extends ErrorOptions,
  Fixed extends ErrorOptions,
> = SimplifyDeep<
  Extract<Merge<Merge<Defaults["context"], Options["context"]>, Fixed["context"]>, ErrorContext>
>;

/**
 * Type of an error factory generated by {@link createError}.
 */
type ErrorFactory<
  Name extends string,
  Defaults extends ErrorOptions,
  Fixed extends ErrorOptions,
> = <const Options extends RemainingErrorOptions<Fixed>>(
  error: Exact<Options, RemainingErrorOptions<Fixed>>,
) => ErrorInstance<
  Name,
  ErrorCode<Fixed, Defaults, Options>,
  ErrorMessage<Fixed, Defaults, Options>,
  ResolvedContext<Defaults, Options, Fixed>
>;

type CreateErrorOptions<
  Name extends string,
  Defaults extends ErrorOptions,
  Fixed extends ErrorOptions,
> = {
  name?: Name;
  defaults?: Defaults;
  fixed?: Fixed;
};

/**
 * Creates a specialized `BaseError` factory.
 *
 * Values are resolved in this order:
 *
 * `defaults` → caller options → `fixed`
 *
 * Because fixed values are merged last, they cannot be overridden at runtime.
 *
 * If neither `defaults.code` nor `fixed.code` is provided, `code` becomes
 * required when calling the generated factory.
 *
 * @example
 * ```ts
 * const NotFoundError = createError({
 *   name: "NotFoundError",
 *   defaults: {
 *     message: "The requested resource was not found",
 *   },
 *   fixed: {
 *     code: "NOT_FOUND",
 *     context: {
 *       internal: {
 *         source: "api",
 *       },
 *     },
 *   },
 * });
 *
 * const error = NotFoundError({
 *   context: {
 *     internal: {
 *       requestId: "123",
 *     },
 *   },
 * });
 * ```
 */
export function createError<
  const Name extends string = "Error",
  const Defaults extends ErrorOptions = {},
  const Fixed extends ErrorOptions = {},
>(options: CreateErrorOptions<Name, Defaults, Fixed>): ErrorFactory<Name, Defaults, Fixed>;
export function createError(options: {
  name?: string;
  defaults?: ErrorOptions;
  fixed?: ErrorOptions;
}): any {
  const name = options.name ?? "Error";

  const GeneratedError = class extends BaseError {
    constructor(error: ErrorOptions) {
      const merged = mergeErrorOptions(options.defaults, error, options.fixed);
      const code = merged.code;

      if (code === undefined) {
        throw new Error("An error code is required");
      }

      super({
        ...merged,
        code,
      });
    }
  };

  Object.defineProperty(GeneratedError, "name", {
    value: name,
    configurable: true,
  });

  function create(error: ErrorOptions) {
    const instance = new GeneratedError(error);

    Object.defineProperty(instance, "name", {
      value: name,
      configurable: true,
      writable: true,
    });

    captureStackTrace(instance, create);

    return instance;
  }

  Object.defineProperty(create, "name", {
    value: name,
    configurable: true,
  });

  create.prototype = GeneratedError.prototype;

  return create;
}

/**
 * Captures the stack while excluding the internal factory frame.
 *
 * This makes the stack point to the call site of the generated error factory.
 */
function captureStackTrace(error: Error, constructor?: Function): void {
  const capture = (
    Error as ErrorConstructor & {
      captureStackTrace?: (targetObject: object, constructorOpt?: Function) => void;
    }
  ).captureStackTrace;

  capture?.(error, constructor);
}

/**
 * Determines whether a value can safely participate in a recursive object merge.
 *
 * Arrays, `null`, and class instances are treated as leaf values.
 */
function isMergeableObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return false;
  }

  const prototype = Object.getPrototypeOf(value);

  return prototype === Object.prototype || prototype === null;
}

/**
 * Recursively merges the provided error options.
 *
 * Later values override earlier values. When both values are mergeable
 * objects, their properties are merged recursively.
 */
function mergeErrorOptions(...options: Array<ErrorOptions | undefined>): ErrorOptions {
  let result: ErrorOptions = {};

  for (const option of options) {
    if (option === undefined) {
      continue;
    }

    result = mergeObjects(result, option);
  }

  return result;
}

/**
 * Recursively merges two plain objects.
 */
function mergeObjects(
  base: Record<string, unknown>,
  override: Record<string, unknown>,
): Record<string, unknown> {
  const result = { ...base };

  for (const [key, value] of Object.entries(override)) {
    const current = result[key];

    result[key] =
      isMergeableObject(current) && isMergeableObject(value) ? mergeObjects(current, value) : value;
  }

  return result;
}
